### ISSUE TITLE
Move public data to a sub-path

### ISSUE THREAD

**Issue by homeworkprod** [psenough/livecode.demozoo.org#40]
**What**

I strongly suggest to introduce a sub-path exclusively for files that should be part of the generated website (i.e. rendered HTML documents, assets).

**How**

GitHub pages has an option to specify a different folder than `/` (in "Settings" → "Pages" → "Source).

In my experience, the `CNAME` file has to be moved to the new path as well.

**Why**

Currently all data from the repository (minus `.git/`, at least) is published as part of the website. This includes the code to generate the site, the original JSON data files, etc. While the data is public on GitHub anyway, it shouldn't be included in what is served as the website.

**PR**

I made #39 which lays a bit of ground work towards moving public website data to a separate path. After that is merged, I would like to attempt a solution to this issue in a new PR.

**Comment by psenough** [comment]
original json files being public is acceptable (we want that data easy to access on server request in case anyone wants to do something with it), but yeah i agree on the rest. having a `/gen/` or `/build/` or `/public/` or something seems much cleaner.

**Comment by homeworkprod** [comment]
`/public` sounds great.

**Comment by homeworkprod** [comment]
I have a branch ready.

**Comment by psenough** [comment]
decided to use gh-pages for the built version instead

**Comment by homeworkprod** [comment]
After a fortunate turn of events, we actually do have a `public/` directory now in which the public files reside! \o/

With the updated workflow, after regenerating the HTML files, the content of `public/` gets copied to a fresh `gh-pages` branch from where GitHub Pages will serve it.
