### ISSUE TITLE
remove the shader royale 2 starting soon from background video

### ISSUE THREAD

**Issue by psenough** [psenough/livecode.demozoo.org#46]
i think we should remove the frames with "shader royale 2 starting soon" text from background video, to avoid having text on background of logo, it's just distracting, doesn't give much info, better edit the video down a bit imho

**Comment by totetmatt** [comment]
Done, One original Idea I got at the begining would be to have some real shader running behind.  Shader from bonzo source would be difficult , but maybe an iframe from shadertoy could do the trick

**Comment by psenough** [comment]
would need to be something light to also run on mobile without performance issues but we can do a call for such, or pick some and ask the authors to use them. the site gargaj was once making to explain what shader showdowns were (that never got finished couz no one bothered to do content for it) had similar boilerplate of background using a few different shaders that were relatively light running on a webgl canvas background.
