### ISSUE TITLE
Cache does not persist new data in current workflow

### ISSUE THREAD

**Issue by homeworkprod** [psenough/livecode.demozoo.org#48]
Since the commit-triggered workflow now commits to branch `gh-pages` instead of `main`, newly downloaded images as well as handles looked up from Demozoo are downloaded again on every run instead of being persisted after the first successful download/lookup to `public/media` and `cache/handles.json`, respectively.

While the Demozoo handle lookup is integrated in the `generate_html.py` script, images are downloaded as a separate workflow step.

I assume we should be able to commit to the `main` branch after the "Download Images" step, then switch to a fresh(!) `gh-pages` brand (as we currently) do, trigger HTML generation, and commit to `gh-pages`.

**Comment by totetmatt** [comment]
Could we have then the `public/media` and `cache/handles.json` commited to main ?

**Comment by homeworkprod** [comment]
Yeah, that's the idea. They are still in `main` anyway (and should be).

**Comment by homeworkprod** [comment]
The images are now downloaded with a new script in a separate step (the original image download step practibally did nothing) and commited to `main`.

A commit with the same message and changes appears on `gh-pages` as well, but seems to be just a lightweight copy somehow.

This change also makes updating a local repository copy faster as the `gh-pages` branch has a smaller diff due to updated images not being included there exclusively anymore.

**Comment by homeworkprod** [comment]
The Demozoo handles are now also updated on `main`, thus get persisted.
